# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend servicee
  app:
    image: node:14.13.1-alpine
    ports:
        - 8081:8080
        - 3031:3030
    volumes:
      - ./:/app/
    environment: 
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mintberry
      DB_TEST_HOST: db_test
    links:
      - db:db
      - db_test:db_test
    tty: true

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mintberry
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /media/leandro/Home/Documents/Projects/docker/mysql-data:/var/lib/mysql

  # Database Service (Mysql)
  db_test:
    image: postgres:13.0-alpine
    ports:
    - "3308:3306"
    restart: always
    environment:
      POSTGRES_PASSWORD: root 
  
