export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const CLEAR_SUCCESS_NOTIFICATIONS = "CLEAR_SUCCESS_NOTIFICATIONS";

export const CLEAR_ALL_NOTIFICATIONS = "CLEAR_ALL_NOTIFICATIONS";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";
