export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const CLEAR_SUCCESS_NOTIFICATIONS = "CLEAR_SUCCESS_NOTIFICATIONS";

export const CLEAR_ERROR_NOTIFICATIONS = "CLEAR_ERROR_NOTIFICATIONS";

export const CLEAR_ALL_NOTIFICATIONS = "CLEAR_ALL_NOTIFICATIONS";

export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";

export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";

export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST";

export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";

export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const SET_TASKS_VISIBILITY_FILTER = "SET_TASKS_VISIBILITY_FILTER";

export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";

export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";

export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";